### PR TITLE
Add comments to the first declaration of the drivetrain functions. In…

### PR DESCRIPTION
**Pull request by jwong101**
…vert the speed being set to the back drivetrain motors

### CODE REVIEW

**Review by LoadingPleaseWait — CHANGES_REQUESTED** [review]
The Doxygen comment starting on line 135 has been separated from the function which it documents. Also, have you tested if this motor inversion works?

**Comment by jwong101** [comment]
Although we haven't tested it with this changed code, the rear wheels of the drivetrain were spinning in the opposite direction that they were supposed to go.

**Comment by LoadingPleaseWait** [comment]
You guys should check the wiring. That isn't natural.

**Comment by jwong101** [comment]
The front drivetrain motors had to be inverted in Lam-Dunk

**Review by LoadingPleaseWait — APPROVED** [review]

**Comment by LoadingPleaseWait** [comment]
It should be the right side or the left side of a drivetrain that has inverted motors because motors on opposite sides of a drivetrain face in different directions.

**Comment by jwong101** [comment]
Alright, we'll check the wiring out.

**Pull request merged**
